title: DITA 2.0 draft
description: DITA 2.0 draft
url: /dita-draft-website/
baseurl: ''

# https://jekyllrb.com/docs/configuration/options/
safe: true
lsi: false
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: compressed
  sass_dir: css

# Major & minor release version (2 digits)
release: '3.3'
# Maintenance version (normally 3 digits, 2 for initial minor release)
version: '3.3.4'

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - images/dita-ot_input-output.graffle
  - LICENSE
  - node_modules
  - package*.js*
  - README.md

# Enable Octicons
plugins:
  - jekyll-octicons
# Force-include Netlify’s redirects file
# https://www.netlify.com/docs/redirects
# include:
#   - _redirects
