name: publish
inputs:
  MAP:
    required: true
  FILTER:
    required: true
  DIR:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: Cache DITA-OT
      uses: actions/cache@v2
      with:
        path: |
          dita-ot-${{ env.DITA_OT_VERSION }}.zip
        key: ${{ runner.os }}-${{ env.DITA_OT_VERSION }}
    - name: Set up DITA-OT
      shell: bash
      run: |
        set -e
        if [ -f "dita-ot-$DITA_OT_VERSION.zip" ]; then
          echo "Use cached $PWD/dita-ot-$DITA_OT_VERSION.zip"
        else
          curl -sfL https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT_VERSION/dita-ot-$DITA_OT_VERSION.zip -o dita-ot-$DITA_OT_VERSION.zip
        fi
        unzip -q dita-ot-$DITA_OT_VERSION.zip
        echo "DITA_HOME=$PWD/dita-ot-$DITA_OT_VERSION" >> $GITHUB_ENV
    - name: Install plug-ins
      shell: bash
      run: |
        cp -r dita-draft-website/_plugin $DITA_HOME/plugins/org.dita-ot.html
        $DITA_HOME/bin/dita install
    - name: Run DITA-OT
      shell: bash
      run: |
        $DITA_HOME/bin/dita \
          -i ${{ inputs.MAP }} \
          -o dita-draft-website/${{ inputs.DIR }} \
          -f org.dita-ot.html \
          --filter=${{ inputs.FILTER }} \
          -v
    - name: Commit changes
      shell: bash
      run: |
        if [ $(git status -s | wc -l) != 0 ]; then
          git config user.email "ditaotbot@gmail.com"
          git config user.name "DITA-OT Bot"
          git add --all
          # Commit generated site output
          git commit -a -m "Deploy oasis-tcs/dita@${GITHUB_SHA:0:7}"
          git log HEAD^1...HEAD
          # push
          git push -v origin master
        else
          echo "Nothing to commit"
        fi
      working-directory: dita-draft-website
