name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DITA_OT_VERSION: '3.6.1'
    steps:
      - uses: actions/checkout@v3
        with:
          path: dita-draft-website
      - uses: actions/checkout@v3
        with:
          repository: 'oasis-tcs/dita'
          ref: 'DITA-2.0'
          path: dita
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Cache DITA-OT
        uses: actions/cache@v2
        with:
          path: |
            dita-ot-${{ env.DITA_OT_VERSION }}.zip
          key: ${{ runner.os }}-${{ env.DITA_OT_VERSION }}
      - name: Set up DITA-OT
        run: |
          set -e
          if [ -f "dita-ot-$DITA_OT_VERSION.zip" ]; then
            echo "Use cached $PWD/dita-ot-$DITA_OT_VERSION.zip"
          else
            curl -sfL https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT_VERSION/dita-ot-$DITA_OT_VERSION.zip -o dita-ot-$DITA_OT_VERSION.zip
          fi
          unzip -q dita-ot-$DITA_OT_VERSION.zip
          echo "DITA_HOME=$PWD/dita-ot-$DITA_OT_VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: 'dita-ot/org.dita-ot.html'
          path: 'dita-ot-${{ env.DITA_OT_VERSION }}/plugins/org.dita-ot.html'
      - name: Install plug-ins
        run: |
          $DITA_HOME/bin/dita install
      - name: Run DITA-OT
        run: |
          $DITA_HOME/bin/dita \
            -i dita/specification/dita-2.0-specification.ditamap \
            -o dita-draft-website \
            -f org.dita-ot.html \
            --filter=dita/specification/resources/DITA2.0-spec.ditaval \
            -v
      - name: Commit changes
        run: |
          if [ $(git status -s | wc -l) != 0 ]; then
            git config user.email "ditaotbot@gmail.com"
            git config user.name "DITA-OT Bot"
            git add --all
            # Commit generated site output
            git commit -a -m "Deploy dita-ot/docs@${GITHUB_SHA:0:7} to 'dev' docs"
            # push
            # git push -v origin master
            git log HEAD^1...HEAD
          else
            echo "Nothing to commit"
          fi
        working-directory: dita-draft-website
